# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode10.3
language: objective-c
xcode_sdk: iphonesimulator11.0

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild -workspace Example/BadgeSegments.xcworkspace -scheme BadgeSegments-Example | xcpretty
- pod lib lint
